#!/usr/bin/env python3
#
# This file is part of parquet_tools.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (http://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
"""
Usage: pq2csv [options] [infile [outfile]]

Specify 'pq2csv --help' to get the a description of what is needed.

This is a stub file to execute pq2csv.py as a command so that the command
line user does not need to add the '.py' suffix this command line tool.
This program is not importable.
"""

# *****************************************************************************
# *                                p q 2 c s v                                *
# *****************************************************************************

from parquet_tools.pq2csv.pq2csv import main

# Simply execute the main routine in the python module
#
main()
